version: '3'

services:
  redis-1:
    image: redis
    ports:
      - "6379:6379"
  redis-2:
    image: redis
    ports:
      - "7379:6379"
  redis-3:
    image: redis
    ports:
      - "8379:6379"